name: project_portal
description: "A new Flutter project."

publish_to:

version: 1.0.4+4

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^4.2.0
  get: ^4.6.5
  http: ^1.1.2
  http_parser: ^4.0.0
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  provider: ^6.1.1
  flutter_material_symbols: ^0.0.4
  delightful_toast: ^1.1.0
  cached_network_image: ^3.2.0
  flutter_svg: ^1.1.6
  jhijri: ">=0.0.4 <2.0.0"
  syncfusion_flutter_charts: ^25.2.5
  local_auth: ^2.1.7
  flutter_otp_text_field: ^1.1.1
  connectivity_plus: ^5.0.1
  json_annotation: ^4.8.0
  json_serializable: ^6.7.0
  animated_custom_dropdown: ^1.5.0
  font_awesome_flutter: ^9.1.0
  dio: ^4.0.0
  sqflite: ^2.0.0
  path: ^1.8.0
  material_dialogs: ^1.1.4
  timeago: ^3.0.2

  image_picker: ^0.8.4+4
  video_player: ^2.8.3

  permission_handler: ^9.1.0
  flutter_inappwebview: ^5.0.0
  chewie: ^1.4.1

  firebase_core: ^2.16.0  # Check for the latest version
  firebase_crashlytics: ^3.4.18


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/en-US.json
    - assets/translations/ar-DZ.json
    - assets/images/

  fonts:
    - family: Kufam
      fonts:
        - asset: assets/font/Kufam.ttf

flutter_intl:
  enabled: true
