# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Add the Firebase Crashlytics pod
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Core'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'  # تأكد من استخدام الإصدار المناسب من Swift
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',          # تمكين إذن الكاميرا
        'PERMISSION_PHOTOS=1',          # تمكين إذن الصور (الاستوديو)
        'PERMISSION_LOCATION=1',        # تمكين إذن الموقع
        'PERMISSION_MICROPHONE=0',      # تعطيل إذن الميكروفون
        'PERMISSION_CONTACTS=0',        # تعطيل إذن جهات الاتصال
        'PERMISSION_EVENTS=0',          # تعطيل إذن الأحداث
        'PERMISSION_REMINDERS=0',       # تعطيل إذن التذكيرات
        'PERMISSION_NOTIFICATIONS=0',   # تعطيل إذن الإشعارات
        'PERMISSION_MEDIA_LIBRARY=0',   # تعطيل إذن مكتبة الوسائط
        'PERMISSION_SPEECH_RECOGNIZER=0', # تعطيل إذن التعرف على الصوت
        'PERMISSION_SENSORS=0',         # تعطيل إذن أجهزة الاستشعار
        'PERMISSION_BLUETOOTH=0',       # تعطيل إذن البلوتوث
      ]
    end
  end
end
